audio:
  state:
    input_devices:
    - audio_buffer_seconds: 20
      calibration_packets: 20
      channels: 2
      device_name: Built-in Microphone
      history_len: 100
      host_id: CoreAudio
      resampler_quality: 5
      sample_format: f32
      sample_rate: 44100
    - audio_buffer_seconds: 20
      calibration_packets: 20
      channels: 2
      device_name: Built-in Microphone
      history_len: 100
      host_id: CoreAudio
      resampler_quality: 5
      sample_format: f32
      sample_rate: 48000
    output_devices:
    - audio_buffer_seconds: 20
      calibration_packets: 20
      channels: 2
      device_name: Built-in Output
      frame_size: 160
      history_len: 100
      host_id: CoreAudio
      resampler_quality: 5
      sample_format: f32
      sample_rate: 44100
stt:
  deepgram_api_key: '87a6f2913693d353b005b7a35959df65c5a54d65'
  enable_speaker_id: false
  keyterm: ''
  speaker_id:
    profiles: {}
    recognition:
      confidence_threshold: 0.7
      learning_mode: true
      max_speakers: 4
      voice_fingerprint_length: 128
